global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'road-traffic'

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'road-traffic'
    scrape_interval: 5s
    static_configs:
      - targets: ['road_traffic_exporter:8080']
    metrics_path: '/metrics'
    metric_relabel_configs:
    - source_labels: ['instance']
      target_label: 'instance'
      action: 'replace'
      replacement: ''